sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: TU5TxbI0q/Pxpj9hMdjv7mXebob/03Jw6XTFYZ6Mbm104sRh030gk/3VeR2zSWVX8lQjII4r/OGMSKmo6/uo6YpFy7qeNBt32qTuITH3GEkmc7RTD9lN98WXLVjFvZwHTaWHP+M/LX/kuD85Fz9c3T0f4QIvtYZISIkCjQQyyp/OOc2/qVqIstIzq/lkxknBZn0M2BpeGLFk7w9kA+85yS5LaKsDPSlpuwc13/UwpJWzG4Zukh4aPJ3hEsoSvWxpKjdJhIazOETHmUBIoZ7dKJriEfBwdTbLJ99LXm16vu8jF7XT+9Q2xUFu7iHs+g7JcDw8wNI6XC+1+liusA2pLgRXuVb9snsqIk94HPwI9BYKPvKkDMcsyXOetVxdmHesD36iPpj5yjZCXW88/zSssczvgRT84j0s9iBPZnw+VzyikYKFx0NPIPslfB8WmBDti4088mDGBiYG4h0NoJuTSo7EFtPX12Pg83yAp65jHzaHQ5PAoCzC8KMjH2TRCZJiqEpbhtM/K2o7BBey1dRr2Dk8DOumoO7ghTUR5ala/F3gIyk5/jt1imHyCqQLxDZYQ7x/TtaSFaf4SwNGAAOELEE8Yx7+5oePnTLmUu91EkE0jK/zULZ9ZmYz3MYrJp7NfU9UuSggfKEb84lId7hnBo8OElQopV5Q2X0cKh43KFg=
  on : heroku_production
  app : probot-tharindukw96